name: qwenie
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - cpython=3.11.13
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.9.19
  - cuda-runtime=12.4.1
  - cuda-version=12.9
  - ffmpeg=4.3
  - filelock=3.19.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.17
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.9.82
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.5.0
  - libuuid=2.41.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=3.0.2
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.5
  - numpy=2.3.3
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.5.2
  - pip=25.2
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.11.9
  - python_abi=3.11
  - pytorch=2.5.0
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - tbb=2021.13.0
  - tk=8.6.13
  - torchtriton=3.1.0
  - torchvision=0.20.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.10.1
      - bitsandbytes==0.47.0
      - blinker==1.9.0
      - click==8.2.1
      - diffusers==0.36.0.dev0
      - flask==3.1.2
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.34.5
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - packaging==25.0
      - pillow==11.3.0
      - psutil==7.0.0
      - regex==2025.9.1
      - safetensors==0.6.2
      - sympy==1.13.1
      - tokenizers==0.22.0
      - tqdm==4.67.1
      - transformers==4.56.1
      - werkzeug==3.1.3
      - zipp==3.23.0
